name: Build

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Build module
        run: |
          chmod +x ./gradlew
          # 替换 module.gradle 描述
          sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
          # 替换 cpp 中包名
          sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
          # 编译 release
          ./gradlew :module:assembleRelease

      - name: Prepare artifact
        run: |
          mkdir -p out/magisk_module_release_named
          cp -r out/magisk_module_release/* out/magisk_module_release_named/${{ github.event.inputs.package_name }}-arm64-release/

      - name: Upload Magisk module
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
          path: out/magisk_module_release_named/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ github.run_id }}"
          name: "Zygisk-Il2CppDumper-${{ github.event.inputs.package_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: out/magisk_module_release_named/${{ github.event.inputs.package_name }}-arm64-release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
