name: Build Zygisk-Il2CppDumper

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Build module
        run: |
          chmod +x ./gradlew
          # 替换 module.gradle 描述
          sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
          # 替换 cpp 中包名
          sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
          # 编译 release
          ./gradlew :module:assembleRelease

      - name: Prepare artifact directory
        run: |
          # 定义输出目录，以包名命名
          PACKAGE_DIR=out/magisk_module_release_named/${{ github.event.inputs.package_name }}
          mkdir -p "$PACKAGE_DIR"
          # 拷贝 Gradle 输出到这个目录
          cp -r module/build/outputs/* "$PACKAGE_DIR/"

      - name: Upload artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }}
          path: out/magisk_module_release_named/${{ github.event.inputs.package_name }}/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ github.run_id }}"
          name: "Zygisk-Il2CppDumper-${{ github.event.inputs.package_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release files
        uses: softprops/action-gh-release@v1
        with:
          files: out/magisk_module_release_named/${{ github.event.inputs.package_name }}/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
